### PR TITLE
Periodically wake `DriverSelect` so we can poll whether or not `stop` had been called.

### LINKED ISSUE #549: `WsServer` not shutting down if a connected client stays idle
Easy to reproduce by [removing the `drop` in this test](https://github.com/paritytech/jsonrpsee/blob/ff3337b107bf29bef6067164c20c6a0b0b5bdc75/tests/tests/integration_tests.rs#L359).

This might be related to the memory leak we see in substrate jsonrpsee branch. Needs a deep dive on the `StopMonitor` and when/how it's being polled.

### PR DESCRIPTION
**Pull request by maciejhirsz**
Fixes #549. This is all pretty esoteric, but TL;DR is:

+ The loop in the per-connection background task has been reworked to more closely resemble the loop in accepting incoming connections, making sure we check the `StopMonitor` every time the driver has been polled.
+ Added an `Interval` internally in `FutureDriver`, which is only polled in the `DriverSelect` instances. It effectively triggers a forced poll every second, which checks the stop flag, which will shut down all loops.

The tests are now properly terminating without having to drop the client (with a 1s delay):

```
$ cargo test --test resource_limiting
   Compiling jsonrpsee-integration-tests v0.4.1 (/home/maciej/rust/jsonrpsee/tests)
    Finished test [unoptimized + debuginfo] target(s) in 2.94s
     Running tests/resource_limiting.rs (target/debug/deps/resource_limiting-17aaec4a6e8ab5eb)

running 4 tests
test http_server_with_macro_module ... ok
test http_server_with_manual_module ... ok
test ws_server_with_manual_module ... ok
test ws_server_with_macro_module ... ok

test result: ok. 4 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 1.00s
```

### CODE REVIEW

**Review by niklasad1 — APPROVED** [review]
LGTM,

Did you run benches by any chance?

File: ws-server/src/future.rs [hunk 1]
```diff
@@ -36,6 +36,10 @@ use std::sync::{
 	Arc, Weak,
 };
 use std::task::{Context, Poll};
+use tokio::time::{self, Duration, Interval};
+
+/// Polling for server stop monitor interval in milliseconds.
+const POLLING_HEARTBEAT: u64 = 1000;
```
Comment (dvdplm) [inline ws-server/src/future.rs:42]:
```suggestion
const STOP_MONITOR_POLLING_INTERVAL: u64 = 1000;
```

File: ws-server/src/future.rs [hunk 2]
```diff
@@ -45,11 +49,16 @@ use std::task::{Context, Poll};
...
 	futures: Vec<F>,
+	heartbeat: Interval,
 }
 
 impl<F> Default for FutureDriver<F> {
 	fn default() -> Self {
-		FutureDriver { futures: Vec::new() }
+		let mut heartbeat = time::interval(Duration::from_millis(POLLING_HEARTBEAT));
+
+		heartbeat.set_missed_tick_behavior(time::MissedTickBehavior::Skip);
```
Comment (dvdplm) [inline ws-server/src/future.rs:59]: TIL

File: ws-server/src/future.rs [hunk 3]
```diff
@@ -92,6 +101,12 @@ where
 			}
 		}
 	}
+
+	fn poll_heartbeat(&mut self, cx: &mut Context) {
```
Comment (dvdplm) [inline ws-server/src/future.rs:105]:
```suggestion
	fn poll_stop_monitor(&mut self, cx: &mut Context) {
```

(Not an accurate name I know, but gives a hint in the right direction?)

File: ws-server/src/server.rs [hunk 4]
```diff
@@ -122,46 +122,64 @@ impl Server {
...
 
 		connections.await
 	}
 }
 
-/// This is a glorified select listening to new connections, while also checking
-/// for `stop_receiver` signal.
-struct Incoming<'a> {
-	listener: TcpListener,
+/// This is a glorified select listening to new messages, while also checking the `stop_receiver` signal.
```
Comment (dvdplm) [inline ws-server/src/server.rs:136]:
```suggestion
/// This is a glorified select listening for new messages, while also checking the `stop_receiver` signal.
```

File: ws-server/src/server.rs [hunk 5]
```diff
@@ -275,31 +293,39 @@ async fn background_task(
...
+			if let Err(err) = method_executors.select_with(Monitored::new(receive, &stop_server)).await {
+				match err {
+					MonitoredError::Selector(SokettoError::Closed) => {
+						tracing::debug!("Remote peer terminated the connection: {}", conn_id);
+						tx.close_channel();
+						return Ok(());
+					}
+					MonitoredError::Selector(SokettoError::MessageTooLarge { current, maximum }) => {
+						tracing::warn!(
+							"WS transport error: message is too big error ({} bytes, max is {})",
```
Comment (dvdplm) [inline ws-server/src/server.rs:314]:
```suggestion
							"WS transport error: outgoing message is too big error ({} bytes, max is {})",
```

File: ws-server/src/server.rs [hunk 6]
```diff
@@ -275,31 +293,39 @@ async fn background_task(
...
+		{
+			// Need the extra scope to drop this pinned future and reclaim access to `data`
+			let receive = receiver.receive_data(&mut data);
+
+			tokio::pin!(receive);
+
+			if let Err(err) = method_executors.select_with(Monitored::new(receive, &stop_server)).await {
+				match err {
+					MonitoredError::Selector(SokettoError::Closed) => {
+						tracing::debug!("Remote peer terminated the connection: {}", conn_id);
```
Comment (dvdplm) [inline ws-server/src/server.rs:308]:
```suggestion
						tracing::debug!("WS transport error: remote peer terminated the connection: {}", conn_id);
```

(not to self, plug in close reason here one day)

File: ws-server/src/future.rs [hunk 7]
```diff
@@ -45,11 +49,16 @@ use std::task::{Context, Poll};
 /// `select_with` providing some other future, the result of which you need.
 pub(crate) struct FutureDriver<F> {
 	futures: Vec<F>,
+	heartbeat: Interval,
```
Comment (dvdplm) [inline ws-server/src/future.rs:52]:
```suggestion
	stop_monitor_heartbeat: Interval,
```

maybe? Either way, some docs here would be good.

**Review by dvdplm — APPROVED** [review]
