### PR TITLE
client: add `Subscription::close_reason`

### LINKED ISSUE #1291: [client]: simplify subscription API
The "current" subscription API for the client doesn't expose how a subscription was closed.

The subscription can return :
    - None: The connection was closed
    - None: The subscription could not keep up with server a.k.a slow-receiver problem.
    - Err(e):  Failed to parse the subscription item as T

Thus, we should modify the API to do the following:
- None: The connection was closed
- Err(SubscriptionError::Lagged) - The subscription lagged too far behind i.e, could not keep up with the server.  The error itself indicates how many messages that were missed. 
- Err(Subscription::Parse) - Failed to decode item as T

#### Some notes about SubscriptionError::Lagged 

When this occurs it's up the user the decide whether that is okay to loose a few messages to continue or re-subscribe.

### PR DESCRIPTION
**Pull request by niklasad1**
This PR changes adds a new API to the subscription know how the subscription was closed.

It still drops the subscription if it's lagging but the subscription should easily-extendable to
implement specific handling for lagging, see the example below

### Example of custom subscription logic

```rust
fn drop_oldest_when_lagging<T: Clone + DeserializeOwned + Send + Sync + 'static>(
	mut sub: Subscription<T>,
	buffer_size: usize,
) -> impl Stream<Item = T> {
	let (mut tx, rx) = async_broadcast::broadcast(buffer_size);

	tx.set_overflow(true);

	tokio::spawn(async move {
		// poll sub, sending msgs to our chan which throws stuff away
		while let Some(n) = sub.next().await {
			let msg = match n {
				Ok(msg) => msg,
				Err(e) => {
					tracing::error!("Failed to recv subscription message: {e}");
					continue;
				}
			};

			tx.try_broadcast(msg).expect("Infallible in overflowing mode; qed");
		}
	});
	rx
}
```

Resolves https://github.com/paritytech/jsonrpsee/issues/1291

### CODE REVIEW

File: examples/examples/client_subscription_drop_oldest_item.rs [hunk 1]
```diff
@@ -0,0 +1,118 @@
...
+	let sub: Subscription<i32> = client.subscribe("subscribe_hello", rpc_params![], "unsubscribe_hello").await?;
+
+	// drop oldest messages from subscription:
+	let mut sub = drop_oldest_when_lagging(sub, 10);
+
+	// Simulate that polling takes a long time.
+	tokio::time::sleep(Duration::from_secs(1)).await;
+
+	// The subscription starts from zero but you can
+	// noticed that many items have been replaced
```
Comment (niklasad1) [inline examples/examples/client_subscription_drop_oldest_item.rs:58]:
```suggestion
	// notice that many items have been replaced
```

File: core/src/client/mod.rs [hunk 2]
```diff
@@ -51,6 +52,31 @@ use serde::de::DeserializeOwned;
 use serde_json::Value as JsonValue;
 use tokio::sync::{mpsc, oneshot};
 
+/// Shared state whether a subscription has lagged or not.
+#[derive(Debug, Clone)]
+pub(crate) struct SubscriptionLagged(Arc<Mutex<bool>>);
```
Comment (jsdw) [inline core/src/client/mod.rs:57]: Any reason not to use `Arc<AtomicBool>` instead? :)

Comment (jsdw) [reply core/src/client/mod.rs:57]: Actually I endedu pthinking more about this and the mutex does offer stronger guarantees I think re ordering! It's probably the safe option regardless without thinking very carefully about it!

File: core/src/client/mod.rs [hunk 3]
```diff
@@ -592,6 +655,61 @@ impl<'a, R> IntoIterator for BatchResponse<'a, R> {
...
+}
+
+pub(crate) struct TooSlow;
+
+impl Stream for SubscriptionReceiver {
+	type Item = Result<JsonValue, TooSlow>;
+
+	fn poll_next(mut self: Pin<&mut Self>, cx: &mut task::Context<'_>) -> task::Poll<Option<Self::Item>> {
+		if self.lagged.has_missed_message() {
+			return Poll::Ready(Some(Err(TooSlow)));
```
Comment (jsdw) [inline core/src/client/mod.rs:698]: I wonder whether a potential issue here is that this "missed messages" thing being set to true doesn't wake up the task. It might be irrelevant though since, if messages are being missed, it is because this thing isn't being polled quickly enough already, so I'm inclined to think it's not an issue.

File: core/src/client/mod.rs [hunk 4]
```diff
@@ -592,6 +655,61 @@ impl<'a, R> IntoIterator for BatchResponse<'a, R> {
...
+				Err(TrySubscriptionSendError::TooSlow(m))
+			}
+		}
+	}
+}
+
+#[derive(Debug)]
+pub(crate) struct SubscriptionReceiver {
+	inner: mpsc::Receiver<JsonValue>,
+	lagged: SubscriptionLagged,
```
Comment (jsdw) [inline core/src/client/mod.rs:688]: It's a shame we need a mutex here, because that's potentially polled a lot, so I wonder what perf impact it has.

Another way to implement this could be to have a channel with CAPACITY + 1, and then if we get up to CAPACITY then push the "Err(MissedMessages)" error to the final vacant slot. Then all subsequent messages are thrown away until the channel starts draining and every time it gets up to CAPACITY again we push another err on. But this could lead to silly things like a whole channel full of such errs if the client is too slow.

I still wonder whether we shouldn't just disconnect them when they are too slow. If they want to avoid it then they use something like in your example here https://github.com/paritytech/jsonrpsee/pull/1320/files#diff-0255f26eec4d19e28d74dcf6bd4ace6bfa5e4e45a1b1e9a63594548150227b60R68. That keeps the impl simple and avoids a mutex at least :)

File: core/src/client/mod.rs (hunk 3 above)
Comment (niklasad1) [reply core/src/client/mod.rs:698]: `has_missed_message` will flip the flag and two reads will end up reading the underlying stream but it's possible that the stream will never be read if the sender/receiver at interleaved:

1. send (full)
2. read (too slow)
3. send (full)
4. read (too slow)
...

and so on but I find it unlikely to be an issue because it should be very unlikely...

File: tests/tests/integration_tests.rs [hunk 5]
```diff
@@ -112,14 +113,15 @@ async fn ws_unsubscription_works() {
...
-	sub.unsubscribe().await.unwrap();
+	sub.unsubscribe().with_default_timeout().await.unwrap().unwrap();
 
 	let res = rx.next().with_default_timeout().await.expect("Test must complete in 1 min");
 	// When the subscription is closed a message is sent out on this channel.
 	assert!(res.is_some());
 }
 
 #[tokio::test]
+#[ignore]
```
Comment (niklasad1) [inline tests/tests/integration_tests.rs:124]:
```suggestion
```

File: examples/examples/client_subscription_drop_oldest_item.rs [hunk 6]
```diff
@@ -0,0 +1,127 @@
...
+	}
+
+	Ok(())
+}
+
+fn drop_oldest_when_lagging<T: Clone + DeserializeOwned + Send + Sync + 'static>(
+	mut sub: Subscription<T>,
+	buffer_size: usize,
+) -> impl Stream<Item = Result<T, BroadcastStreamRecvError>> {
+	let (tx, rx) = tokio::sync::broadcast::channel(buffer_size);
```
Comment (jsdw) [inline examples/examples/client_subscription_drop_oldest_item.rs:80]: Ooh I didn't realise that this channel handled lagging messages, TIL :)

**Review by jsdw — APPROVED** [review]
Cool! Looks good to me :)

File: core/src/client/mod.rs [hunk 7]
```diff
@@ -262,64 +302,85 @@ impl<Notif> Subscription<Notif> {
...
 	}
+
+	/// The reason why the subscription was closed.
+	///
+	/// Returns Some(reason) is the subscription was closed otherwise
+	/// None is returned.
+	pub fn close_reason(&self) -> Option<SubscriptionCloseReason> {
+		let lagged = self.rx.lagged.has_lagged();
+
+		// The `is_closed` is only set if the subscription has been polled
```
Comment (niklasad1) [inline core/src/client/mod.rs:317]:
```suggestion
		// `is_closed` is only set if the subscription has been polled
```

**Review by lexnv — APPROVED** [review]
LGTM! Nice one 👍 

With this PR we should have a bit more info about what happens when the subscription stream ends, which makes our life easier when debugging connectivity issues 🙏
