### PR TITLE
fix(http server): handle post and option HTTP requests properly.

### LINKED ISSUE #628: how  can i  retun  a custom response header?
Now I want to add custom HTTP header information in the reponse structure after the request and return it to the client .
Or how can I solve the cross domain problem through web requests
image

However, I still encounter the same problem in the way I operate on the document, as shown in the following code

image

### PR DESCRIPTION
**Pull request by niklasad1**
Partly fixes https://github.com/paritytech/jsonrpsee/issues/628

### CODE REVIEW

File: http-server/src/response.rs [hunk 1]
```diff
@@ -107,3 +107,13 @@ fn from_template<S: Into<hyper::Body>>(
 pub fn ok_response(body: String) -> hyper::Response<hyper::Body> {
 	from_template(hyper::StatusCode::OK, body, JSON)
 }
+
+
```
Comment (niklasad1) [inline http-server/src/response.rs:111]:
```suggestion
```

**Review by TarikGul — APPROVED** [review]

File: http-server/src/server.rs [hunk 2]
```diff
@@ -301,11 +301,15 @@ impl<M: Middleware> Server<M> {
...
 					// two cases: a single RPC request or a batch of RPC requests.
 					async move {
-						if let Err(e) = access_control_is_valid(&access_control, &request) {
-							return Ok::<_, HyperError>(e);
-						}
+						// Only `POST` and `OPTIONS` methods are allowed.
+						match *request.method() {
+							Method::POST if content_type_is_json(&request) => (),
+							Method::POST => return Ok::<_, HyperError>(response::unsupported_content_type()),
+							Method::OPTIONS => return Ok::<_, HyperError>(response::ok_response("".into())),
```
Comment (jsdw) [inline http-server/src/server.rs:308]: I think we should also run `access_control_is_valid` in this OPTIONS branch because at least one of the checks it does it on a header only provided as part of the preflight request.

File: http-server/src/server.rs [hunk 3]
```diff
@@ -301,11 +301,15 @@ impl<M: Middleware> Server<M> {
 					// Run some validation on the http request, then read the body and try to deserialize it into one of
 					// two cases: a single RPC request or a batch of RPC requests.
 					async move {
-						if let Err(e) = access_control_is_valid(&access_control, &request) {
-							return Ok::<_, HyperError>(e);
-						}
+						// Only `POST` and `OPTIONS` methods are allowed.
+						match *request.method() {
+							Method::POST if content_type_is_json(&request) => (),
```
Comment (jsdw) [inline http-server/src/server.rs:306]: perhaps combine with the below to avoid needing an empty match body?

eg:

```
match *request.method() {
    Method::POST if !content_type_is_json(&request) => return Ok::<_, HyperError>(response::unsupported_content_type()),
   // ...
```

File: http-server/src/server.rs [hunk 4]
```diff
@@ -302,116 +302,25 @@ impl<M: Middleware> Server<M> {
 					// two cases: a single RPC request or a batch of RPC requests.
 					async move {
 						if let Err(e) = access_control_is_valid(&access_control, &request) {
```
Comment (niklasad1) [inline http-server/src/server.rs:304]: this became hard to review, however validate origins and headers before checking the method kind.

File: http-server/src/server.rs [hunk 5]
```diff
@@ -469,3 +375,110 @@ fn is_json(content_type: Option<&hyper::header::HeaderValue>) -> bool {
 		_ => false,
 	}
 }
+
+/// Process a verified request, it implies a POST request with content type JSON.
+async fn process_validated_request(
```
Comment (niklasad1) [inline http-server/src/server.rs:380]: move to a separate function to decrease the indentation level and become more readable...

File: tests/tests/integration_tests.rs [hunk 6]
```diff
@@ -373,3 +373,139 @@ async fn ws_batch_works() {
...
+
+	// Assuming that that was successful, we now make the actual request. No CORS headers are needed here
+	// as the browser checked their validity in the preflight request.
+	let req = Request::builder()
+		.method(Method::POST)
+		.uri(&uri)
+		.header("host", "bar.com")
+		.header("origin", "https://foo.com")
+		.header("content-type", "application/json")
+		.body(Body::from(r#"{ "jsonrpsee": "2.0", method: "say_hello", "id": 1 }"#))
```
Comment (niklasad1) [inline tests/tests/integration_tests.rs:497]: ? :)

```suggestion
		.body(Body::from(r#"{ "jsonrpc": "2.0", method: "say_hello", "id": 1 }"#))
```

Comment (jsdw) [reply tests/tests/integration_tests.rs:497]: Whoops! I guess the server didn't actually care :D

File: tests/tests/integration_tests.rs [hunk 7]
```diff
@@ -373,3 +373,139 @@ async fn ws_batch_works() {
...
+
+	let http_client = Client::new();
+	let uri = format!("http://{}", server_addr);
+
+	let req_is_client_error = |method| async {
+		let req = Request::builder()
+			.method(method)
+			.uri(&uri)
+			.header("content-type", "application/json")
+			.body(Body::from(r#"{ "jsonrpsee": "2.0", method: "say_hello", "id": 1 }"#))
```
Comment (niklasad1) [inline tests/tests/integration_tests.rs:391]: I guess the body is irrelevant for this as the we only care of about the HTTP status?

Comment (jsdw) [reply tests/tests/integration_tests.rs]: That was my thinking; the body was probably tested elsewhere anyway :)

File: tests/tests/integration_tests.rs [hunk 8]
```diff
@@ -373,3 +373,139 @@ async fn ws_batch_works() {
...
+		.expect("preflight request builder");
+
+	let has = |v: &[String], s| v.iter().any(|v| v == s);
+
+	let preflight_res = http_client.request(preflight_req).await.unwrap();
+	let preflight_headers = preflight_res.headers();
+
+	let allow_origins = comma_separated_header_values(&preflight_headers, "access-control-allow-origin");
+	let allow_methods = comma_separated_header_values(&preflight_headers, "access-control-allow-methods");
+	let allow_headers = comma_separated_header_values(&preflight_headers, "access-control-allow-headers");
```
Comment (niklasad1) [inline tests/tests/integration_tests.rs:479]:
```suggestion
	let allow_headers = comma_separated_header_values(preflight_headers, "access-control-allow-headers");
```

Comment (niklasad1) [inline tests/tests/integration_tests.rs]:
```suggestion
	let allow_headers = comma_separated_header_values(preflight_headers, "access-control-allow-headers");
```

File: tests/tests/integration_tests.rs [hunk 9]
```diff
@@ -373,3 +373,139 @@ async fn ws_batch_works() {
...
+		.body(Body::empty())
+		.expect("preflight request builder");
+
+	let has = |v: &[String], s| v.iter().any(|v| v == s);
+
+	let preflight_res = http_client.request(preflight_req).await.unwrap();
+	let preflight_headers = preflight_res.headers();
+
+	let allow_origins = comma_separated_header_values(&preflight_headers, "access-control-allow-origin");
+	let allow_methods = comma_separated_header_values(&preflight_headers, "access-control-allow-methods");
```
Comment (niklasad1) [inline tests/tests/integration_tests.rs:478]:
```suggestion
	let allow_methods = comma_separated_header_values(preflight_headers, "access-control-allow-methods");
```

File: tests/tests/integration_tests.rs [hunk 10]
```diff
@@ -373,3 +373,139 @@ async fn ws_batch_works() {
...
+		.header("access-control-request-headers", "content-type")
+		.body(Body::empty())
+		.expect("preflight request builder");
+
+	let has = |v: &[String], s| v.iter().any(|v| v == s);
+
+	let preflight_res = http_client.request(preflight_req).await.unwrap();
+	let preflight_headers = preflight_res.headers();
+
+	let allow_origins = comma_separated_header_values(&preflight_headers, "access-control-allow-origin");
```
Comment (niklasad1) [inline tests/tests/integration_tests.rs:477]:
```suggestion
	let allow_origins = comma_separated_header_values(preflight_headers, "access-control-allow-origin");
```

File: tests/tests/integration_tests.rs [hunk 11]
```diff
@@ -373,3 +373,139 @@ async fn ws_batch_works() {
...
+
+	let res = http_client.request(req).await.unwrap();
+	assert!(res.status().is_success());
+}
+
+fn comma_separated_header_values(headers: &hyper::HeaderMap, header: &str) -> Vec<String> {
+	headers
+		.get_all(header)
+		.into_iter()
+		.flat_map(|value| value.to_str().unwrap().split(",").map(|val| val.trim()))
```
Comment (niklasad1) [inline tests/tests/integration_tests.rs:508]:
```suggestion
		.flat_map(|value| value.to_str().unwrap().split(',').map(|val| val.trim()))
```

**Review by maciejhirsz — APPROVED** [review]
Nice!

File: examples/cors_server.rs [hunk 12]
```diff
@@ -0,0 +1,82 @@
...
+
+	// Start up a JSONPRC server that allows cross origin requests.
+	let (server_addr, _handle) = run_server().await?;
+
+	// Print instructions for testing CORS from a browser.
+	println!("Run the following snippet in the developer console in any Website.");
+	println!(
+		r#"
+        fetch("http://{}", {{
+            method:  'POST',
```
Comment (niklasad1) [inline examples/cors_server.rs:46]:
```suggestion
            method: 'POST',
```
