### PR TITLE
fix: tokio v1.27

### LINKED ISSUE #1059: CI: broken after tokio v1.27.0
The CI is broken after the latest tokio release v1.27.0

### PR DESCRIPTION
**Pull request by niklasad1**
Tokio v1.27 changed how interval/timers are woken up.

Because we already have `async fn StopHandle::shutdown` we could just select on that along with the other future.
Thus, these periodically wake-ups are not needed anymore which should fix this properly.

Close #1059

### CODE REVIEW

File: server/src/transport/ws.rs [hunk 1]
```diff
@@ -519,3 +467,71 @@ async fn send_task(
...
+	receiver: &mut Receiver,
+	mut data: &mut Vec<u8>,
+	method_executor: &mut FutureDriver<F>,
+	stopped: S,
+) -> Receive<S>
+where
+	F: Future + Unpin,
+	S: Future<Output = ()> + Unpin,
+{
+	// Need the extra scope to drop this pinned future and reclaim access to `data`
```
Comment (niklasad1) [inline server/src/transport/ws.rs:487]:
```suggestion
```

File: server/src/transport/ws.rs [hunk 2]
```diff
@@ -519,3 +467,70 @@ async fn send_task(
...
+	stopped: S,
+) -> Receive<S>
+where
+	F: Future + Unpin,
+	S: Future<Output = ()> + Unpin,
+{
+	let receive = async {
+		// Identical loop to `soketto::receive_data` with debug logs for `Pong` frames.
+		loop {
+			match receiver.receive(&mut data).await? {
```
Comment (niklasad1) [inline server/src/transport/ws.rs:490]:
```suggestion
			match receiver.receive(data).await? {
```

File: server/src/transport/ws.rs [hunk 3]
```diff
@@ -519,3 +467,70 @@ async fn send_task(
...
+
+enum Receive<S> {
+	Shutdown,
+	Err(SokettoError, S),
+	Ok(S),
+}
+
+async fn try_recv<F, S>(
+	receiver: &mut Receiver,
+	mut data: &mut Vec<u8>,
```
Comment (niklasad1) [inline server/src/transport/ws.rs:479]:
```suggestion
	data: &mut Vec<u8>,
```

File: server/src/future.rs [hunk 4]
```diff
@@ -94,12 +85,6 @@ where
 			}
 		}
 	}
-
-	fn poll_stop_monitor_heartbeat(&mut self, cx: &mut Context) {
-		// We don't care about the ticks of the heartbeat, it's here only
-		// to periodically wake the `Waker` on `cx`.
-		let _ = self.stop_monitor_heartbeat.poll_tick(cx);
```
Comment (lexnv) [inline server/src/future.rs:101]: IIUC we relied on this to make sure that we wake up:
- when there's no scheduled tasks that would yield to the executor (call waker.wake())
- for at most one second 

To remove `tokio::time::Interval` we are polling the `FutureDriver` alongside other operations that we do in the server:
- try_accept_conn: Await incoming connection
- wait_for_permit: Await backpressure for some internal buffer space
- try_recv: Can wait for `soketto::Pong`, `soketto::Data`,  and `soketto::Closed`

Could we still get in a situation where we have no other competing tasks to drive the `FutureDriver`?
(ie, we don't have `soketto::Pong` to wake us up -- or is configured at 100seconds -- and we don't receive `soketto::Data`)

Comment (jsdw) [reply server/src/future.rs:101]: After convincing myself that this DriverSelect thing (ie `select_with`) will poll the futures in itself as needed, maybe I'm missing something but why does it matter if this thing doesn't wake up for a while if none of the futures in it need to progress?

Comment (niklasad1) [reply server/src/future.rs:101]: so, that's good question/observation but I found that quite unlikely because both batch and calls are executed as one future/task.

Then in each loop iteration both `try_recv` and `wait_for_permit` are awaited on which checks "future vec" but not sure if there is possible to spawn huge futures and then "never send some data again/backpressure kicks in" then those would never woken up again but I don't see it as an issue because it's to the client enforce that.

If it's idle fine but we could have a few ready tasks in the vec.

File: server/src/server.rs [hunk 5]
```diff
@@ -167,7 +168,7 @@ where
 			}
 		}
 
-		connections.await;
+		while connections.next().await.is_some() {}
```
Comment (jsdw) [inline server/src/server.rs:171]: Ah ok, so if I understand this right, `FuturesUnordered` won't poll anything until you tell it to, so you are spawning tasks into it and then this line just makes sure that all tasks are completed before the function ends?

Comment (niklasad1) [reply server/src/server.rs:171]: yeah, exactly

**Review by jsdw — APPROVED** [review]
From what I understand of this, it looks good to me!

It'd be interesting to see what, if any, effect this has on benchmarks :)

**Review by lexnv — APPROVED** [review]
LGTM! 👍
