### PR TITLE
[ws client]: fix propogate error in subscription response

### LINKED ISSUE #349: [types client]: Subscription::next() propogate error when parsing the response fails.
When the wrong type is assigned in the `Subscription<T>`, then it's never propagated to the user as any malformed responses are ignored, [see docs here](https://docs.rs/jsonrpsee-types/0.2.0-alpha.7/jsonrpsee_types/struct.Subscription.html#method.next)

That should be changed to propagate when parsing the response fails, as it's not easy detect why no subscription responses are received unless the logs are read.

### PR DESCRIPTION
**Pull request by niklasad1**
Fixes #349 and removes some boiler plate to unify `Subscription` and `NotificationHandler`.

Renamed it `Notification`, technically it as handle for "subscribing" to either a subscription ID or method name.

### CODE REVIEW

File: types/src/traits.rs [hunk 1]
```diff
@@ -45,8 +48,10 @@ pub trait SubscriptionClient: Client {
 	where
 		Notif: DeserializeOwned;
 
-	/// Register a NotificationHandler<Notif> that will listen for incoming JSON-RPC notifications
-	async fn register_notification<'a, Notif>(&self, method: &'a str) -> Result<NotificationHandler<Notif>, Error>
+	/// Register a method subscription, the method name is used to only propogate
```
Comment (niklasad1) [inline types/src/traits.rs:51]:
```suggestion
	/// Register a method subscription, this is used to filter only server notifications that a user is interested in.
```

File: tests/tests/integration_tests.rs [hunk 2]
```diff
@@ -48,8 +48,8 @@ async fn ws_subscription_works() {
 		client.subscribe("subscribe_foo", JsonRpcParams::NoParams, "unsubscribe_foo").await.unwrap();
 
 	for _ in 0..10 {
-		let hello = hello_sub.next().await.unwrap();
-		let foo = foo_sub.next().await.unwrap();
+		let hello = hello_sub.next().await.unwrap().unwrap();
+		let foo = foo_sub.next().await.unwrap().unwrap();
 		assert_eq!(&hello, "hello from subscription");
 		assert_eq!(foo, 1337);
```
Comment (dvdplm) [inline tests/tests/integration_tests.rs:54]:
```suggestion
		let hello = hello_sub.next().await.unwrap();
		let foo = foo_sub.next().await.unwrap();
		assert_eq!(hello, Some("hello from subscription".into()));
		assert_eq!(foo, Some(1337));
```

Maybe it's easier to read rather than the double `.unwrap()`?

File: types/src/client.rs [hunk 3]
```diff
@@ -109,63 +117,31 @@ where
 	Notif: DeserializeOwned,
 {
 	/// Returns the next notification from the stream
```
Comment (dvdplm) [inline types/src/client.rs:119]:
```suggestion
	/// Returns the next notification from the stream.
```

File: types/src/client.rs [hunk 4]
```diff
@@ -109,63 +117,31 @@ where
...
-}
-
-impl<Notif> NotificationHandler<Notif>
-where
-	Notif: DeserializeOwned,
-{
-	/// Returns the next notification from the stream
-	/// This may return `None` if the method has been unregistered,
+	/// This may return `Ok(None)` if the subscription has been terminated,
 	/// may happen if the channel becomes full or is dropped.
```
Comment (dvdplm) [inline types/src/client.rs:121]:
```suggestion
	/// Returns `Ok(None)` if the subscription has been terminated on the server side, e.g. the server dropped the
	/// connection, crashed, or dropped the connection for whatever reason.
```

I am not sure I understand how the channel being full would cause `None`. Can you help me understand? Wouldn't that mean that the server can't send messages on it but the client could still read from it?

File: types/src/traits.rs [hunk 5]
```diff
@@ -45,8 +48,10 @@ pub trait SubscriptionClient: Client {
 	where
 		Notif: DeserializeOwned;
 
-	/// Register a NotificationHandler<Notif> that will listen for incoming JSON-RPC notifications
-	async fn register_notification<'a, Notif>(&self, method: &'a str) -> Result<NotificationHandler<Notif>, Error>
+	/// Register a method subscription, this is used to filter only server notifications that a user is interested in.
+	///
+	/// The `Notif` param is a generic type to receive generic subscriptions, see [`Subscription`](crate::client::Subscription) for further documentation.
```
Comment (dvdplm) [inline types/src/traits.rs:53]:
```suggestion
	/// The `Notif` param is a generic type to receive generic subscriptions, see [`Subscription`] for further documentation.
```

File: types/src/traits.rs [hunk 6]
```diff
@@ -28,11 +28,14 @@ pub trait Client {
...
+	/// a `Subscription ID` that is used to fetch messages on that subscription,
 	///
 	/// The `subscribe_method` and `params` are used to ask for the subscription towards the
 	/// server.
 	///
+	/// The params may be used as input for the subscription for the server to process.
+	///
 	/// The `unsubscribe_method` is used to close the subscription.
 	///
 	/// The `Notif` param is a generic type to receive generic subscriptions, see [`Subscription`](crate::client::Subscription) for further documentation.
```
Comment (dvdplm) [inline types/src/traits.rs:41]:
```suggestion
	/// The `Notif` param is a generic type to receive generic subscriptions, see [`Subscription`] for further documentation.
```

**Review by dvdplm — APPROVED** [review]

File: ws-client/src/client.rs [hunk 7]
```diff
@@ -455,12 +455,11 @@ impl SubscriptionClient for WsClient {
...
 		};
-		Ok(Subscription { to_back: self.to_back.clone(), notifs_rx, marker: PhantomData, id })
+		Ok(Subscription::new(self.to_back.clone(), notifs_rx, SubscriptionKind::Subscription(id)))
 	}
 
-	/// Register a notification handler for async messages from the server.
-	///
-	async fn register_notification<'a, N>(&self, method: &'a str) -> Result<NotificationHandler<N>, Error>
+	/// Subscribe to a specific method.
+	async fn subscribe_method<'a, N>(&self, method: &'a str) -> Result<Subscription<N>, Error>
```
[the remark this answers is not in the document]
Comment (niklasad1) [reply ws-client/src/client.rs:466]: I like `subscribe_to_method`

**Review by dvdplm — APPROVED** [review]
