### PR TITLE
fix(server): fix leak in FuturesUnordered

### LINKED ISSUE #1200: High memory consumption after 0.16.x
It look like #1150 .

It will use 5MB memory, when I send every 3000 message by a WebSocket connection.

Test way:
```js
var rpc_data = {
	"jsonrpc": "2.0",
	"method": "hello",
	"params": [],
	"id": 2
};
var ws = new WebSocket("ws://192.168.2.3:3030");

ws.onopen = ()=>{
	console.log("open ws");
	ws.send(JSON.stringify(rpc_data));
};
ws.onmessage = (data)=>{
	console.log("recv");
	ws.send(JSON.stringify(rpc_data));
}
```

### PR DESCRIPTION
**Pull request by niklasad1**
FuturesUnordered was not getting polled until shutdown, so it was accumulating tasks forever. The change uses a channel instead to wait until all senders are closed before shutdown can happen.

Reduces the memory usage significantly but still slightly worse than v0.16.x, around 2x but that should be okay.

Close #1200

### CODE REVIEW

**Review by jsdw — APPROVED** [review]
LGTM; nice catch! FuturesUnordered was not getting polled until shutdown, so it was accumulating tasks forever. The change uses a channel instead to wait until all senders are closed before shutdown can happen.

File: server/src/transport/ws.rs [hunk 1]
```diff
@@ -550,6 +559,8 @@ async fn execute_unchecked_call<L: Logger>(params: Arc<ExecuteCallParams<L>>, da
 			_ = params.sink.send_error(Id::Null, ErrorCode::ParseError.into()).await;
 		}
 	};
+
+	drop(drop_on_completion);
```
Comment (niklasad1) [inline server/src/transport/ws.rs:563]:
```suggestion
    // NOTE: This channel is only used to indicate that a method call was completed
    // thus the drop here tells the main task that method call was completed.
	drop(drop_on_completion);
```

**Review by lexnv — APPROVED** [review]
