### PR TITLE
middleware: fix option_layer

### LINKED ISSUE #1560: middleware: RpcServerBuilder::option_layer broken

### PR DESCRIPTION
**Pull request by niklasad1**
Close https://github.com/paritytech/jsonrpsee/issues/1560

The wrong Either type was used which doesn't implement the RpcServiceT

### CODE REVIEW

**Review by lexnv — APPROVED** [review]

File: examples/examples/rpc_middleware.rs [hunk 1]
```diff
@@ -209,7 +249,9 @@ async fn run_server() -> anyhow::Result<SocketAddr> {
 		// This state is created per connection.
 		.layer_fn(|service| CallsPerConn { service, count: Default::default(), role: "server" })
 		// This state is shared by all connections.
-		.layer_fn(move |service| GlobalCalls { service, count: global_cnt.clone(), role: "server" });
+		.layer_fn(move |service| GlobalCalls { service, count: global_cnt.clone(), role: "server" })
+		// Optional layer that does not do anything, useful if have an optional layer.
```
Comment (niklasad1) [inline examples/examples/rpc_middleware.rs:253]:
```suggestion
		// Optional layer that does nothing, just an example to be useful if one has an optional layer.
```
