### PR TITLE
client(error): make display impl less verbose

### LINKED ISSUE #1280: core::ClientError: improve Display impl
The display implementations of [ClientError](https://github.com/paritytech/jsonrpsee/blob/master/core/src/client/error.rs#L35) should be improved for instance an I/O error when the background task got closed generates the following:

```bash
The background task been terminated because: Networking or low-level protocol error: WebSocket connection erro
r: i/o error: Transport endpoint is not connected (os error 107); restart required
```

Lots are redundant information and the I/O part should be sufficient.

### PR DESCRIPTION
**Pull request by niklasad1**
Resolves #1280

### CODE REVIEW

**Review by jsdw — APPROVED** [review]
So basically this change restricts the body error type a bit and as such can avoid the generic boxed error (and a couple of display tweaks)?

Looks good to me!

**Review by lexnv — APPROVED** [review]

File: core/src/http_helpers.rs [hunk 1]
```diff
@@ -61,7 +67,7 @@ where
 	let mut is_single = None;
 
 	while let Some(d) = body.data().await {
-		let data = d.map_err(|e| GenericTransportError::Inner(anyhow!(e.into())))?;
+		let data = d.map_err(|e| HttpError::Stream(e))?;
```
Comment (niklasad1) [inline core/src/http_helpers.rs:70]:
```suggestion
		let data = d.map_err(HttpError::Stream)?;
```
