### PR TITLE
Better error messages for method arguments ignored with a `_`

### LINKED ISSUE #609: [proc_macros]: `_` as ident doesn't work
```
use jsonrpsee_proc_macros::rpc;
use bytes::Bytes;

#[rpc(server)]
pub trait ARpc {

    #[method(name = "a")]
    async fn a(&self, _: Bytes);
}
```
will report:
```
error: custom attribute panicked
   |
14 | #[rpc(server)]
   | ^^^^^^^^^^^^^^
   |
   = help: message: Identifier in signature must be an ident
```

### PR DESCRIPTION
**Pull request by dvdplm**
Fixes #609

### CODE REVIEW

File: proc-macros/src/rpc_macro.rs [hunk 1]
```diff
@@ -81,11 +82,18 @@ impl RpcMethod {
 			.filter_map(|arg| match arg {
 				syn::FnArg::Receiver(_) => None,
 				syn::FnArg::Typed(arg) => match *arg.pat {
-					syn::Pat::Ident(name) => Some((name, *arg.ty)),
-					_ => panic!("Identifier in signature must be an ident"),
+					syn::Pat::Ident(name) => Some(Ok((name, *arg.ty))),
+					syn::Pat::Wild(_) => Some(Err(syn::Error::new(
+						span,
+						"Method argument names must be a valid Rust identifiers; got `_` instead",
```
Comment (TarikGul) [inline proc-macros/src/rpc_macro.rs:88]: Not sure what the correct verbage would be in order to correctly express the error behind the syntax, but it sounds like to me it would be either:

"be a valid Rust identifier"

or

"be valid Rust identifiers"

Comment (dvdplm) [reply proc-macros/src/rpc_macro.rs]: ty! :)

**Review by niklasad1 — APPROVED** [review]
LGTM,

I had no idea that `_` isn't a valid rust identifier.

File: proc-macros/src/rpc_macro.rs [hunk 2]
```diff
@@ -81,11 +82,18 @@ impl RpcMethod {
...
+						"Method argument names must be valid Rust identifiers; got `_` instead",
+					))),
+					_ => Some(Err(syn::Error::new(
+						span,
+						format!("Unexpected method signature input; got {:?} ", *arg.pat),
+					))),
 				},
 			})
-			.collect();
+			.collect::<Result<Vec<_>, _>>()?;
```
Comment (maciejhirsz) [inline proc-macros/src/rpc_macro.rs:96]:
```suggestion
			.collect::<Result<_, _>>()?;
```

Or remove `Vec<_>` on line 79.

File: proc-macros/src/rpc_macro.rs [hunk 3]
```diff
@@ -81,11 +82,18 @@ impl RpcMethod {
 			.filter_map(|arg| match arg {
 				syn::FnArg::Receiver(_) => None,
 				syn::FnArg::Typed(arg) => match *arg.pat {
-					syn::Pat::Ident(name) => Some((name, *arg.ty)),
-					_ => panic!("Identifier in signature must be an ident"),
+					syn::Pat::Ident(name) => Some(Ok((name, *arg.ty))),
+					syn::Pat::Wild(_) => Some(Err(syn::Error::new(
+						span,
```
Comment (maciejhirsz) [inline proc-macros/src/rpc_macro.rs:87]: Couldn't we get the span for the token itself here so the highlight actually shows what the problem is?

**Review by maciejhirsz — APPROVED** [review]
Looks good, minor nits.

File: proc-macros/src/rpc_macro.rs (hunk 3 above)
Comment (dvdplm) [reply proc-macros/src/rpc_macro.rs]: Absolutely, fixed.
